argo-cd:
  configs:
    cm:
      kustomize.buildOptions: "--enable-helm --load-restrictor LoadRestrictionsNone"
    credentialTemplates:
      github:
        url: https://github.com/hdti-devops
    repositories:
      gitops-test:
        url: https://github.com/hdti-devops/gitops-test.git
        name: gitops-test
        type: git